CREATE TABLE superstore (
    row_id INT PRIMARY KEY,
    order_id NVARCHAR(50),
    order_date DATE,
    ship_date DATE,
    ship_mode NVARCHAR(50),
    customer_id NVARCHAR(50),
    customer_name NVARCHAR(100),
    segment NVARCHAR(50),
    country NVARCHAR(50),
    city NVARCHAR(100),
    state NVARCHAR(50),
    postal_code NVARCHAR(20),
    region NVARCHAR(50),
    product_id NVARCHAR(50),
    category NVARCHAR(50),
    sub_category NVARCHAR(50),
    product_name NVARCHAR(MAX),
    sales DECIMAL(10,2),
    quantity INT,
    discount DECIMAL(5,2),
    profit DECIMAL(10,2)
);